#!/usr/bin/env ruby
# Copyright (C) 2013-2016 all contributors <dtas-all@nongnu.org>
# License: GPL-3.0+ <https://www.gnu.org/licenses/gpl-3.0.txt>
# frozen_string_literal: true
CONSTANT = "DTAS::VERSION"
RVF = "lib/dtas/version.rb"
GVF = "GIT-VERSION-FILE"
DEF_VER = "v0.15.0"
vn = DEF_VER

# First see if there is a version file (included in release tarballs),
# then try git-describe, then default.
if File.exist?(".git")
  describe = `git describe --abbrev=4 HEAD 2>/dev/null`.strip
  case describe
  when /\Av[0-9]*/
    vn = describe
    system(*%w(git update-index -q --refresh))
    unless `git diff-index --name-only HEAD --`.chomp.empty?
      vn << "-dirty"
    end
    vn.tr!('-', '.')
  end
end

vn = vn.sub(/\Av/, "")
new_ruby_version = "#{CONSTANT} = '#{vn}'.freeze # :nodoc:\n"
cur_ruby_version = File.read(RVF) rescue nil
if new_ruby_version != cur_ruby_version
  File.open(RVF, "w") { |fp| fp.write(new_ruby_version) }
end
File.chmod(0644, RVF)

# generate the makefile snippet
new_make_version = "VERSION = #{vn}\n"
cur_make_version = File.read(GVF) rescue nil
if new_make_version != cur_make_version
  File.open(GVF, "w") { |fp| fp.write(new_make_version) }
end
File.chmod(0644, GVF)

puts vn if $0 == __FILE__
