% dtas-msinkctl(1) dtas user manual

=head1 NAME

dtas-msinkctl - activate/deactivate multiple sinks at once

=head1 SYNOPSYS

dtas-msinkctl COMMAND
dtas-msinkctl COMMAND [SINKS...]

=head1 DESCRIPTION

dtas-msinkctl is useful for activating/deactivating multiple sinks.

=head1 EXAMPLES

Display only active sinks (unlike "dtas-ctl sink ls", which shows all sinks)

    dtas-msinkctl active

Display only non-blocking sinks

    dtas-msinkctl nonblock

Enable only SINK1 and SINK3, and close other sinks

    dtas-msinkctl active-set SINK1 SINK3

Add the default sink to the active set

    dtas-msinkctl active-add default

Remove SINK3 from the active set

    dtas-msinkctl active-add SINK3

=head1 ENVIRONMENT

DTAS_PLAYER_SOCK - the path to the dtas-player control socket.
This defaults to ~/.dtas/player.sock

=head1 CONTACT

All feedback welcome via plain-text mail to: L<mailto:dtas-all@nongnu.org>

Mailing list archives available at L<https://80x24.org/dtas-all/>
and L<ftp://lists.gnu.org/dtas-all/>

No subscription is necessary to post to the mailing list.

=head1 COPYRIGHT

Copyright 2013-2016 all contributors L<mailto:dtas-all@nongnu.org>

License: GPL-3.0+ L<https://www.gnu.org/licenses/gpl-3.0.txt>

=head1 SEE ALSO

L<dtas-player(1)>, L<dtas-player_protocol(7)>, L<dtas-ctl(1)>,
L<dtas-sinkedit(1)>
