% dtas-archive(1) dtas user manual

=head1 NAME

dtas-archive - paranoid audio file copy

=head1 SYNOPSYS

dtas-archive [OPTIONS] SOURCE DESTINATION

=head1 DESCRIPTION

dtas-archive is intended for archiving audio data to/from laptops,
marginal USB ports, and computers without ECC memory, attempting
to read data multiple times in an attempt to detect memory or
bus corruption.  dtas-archive may only be effective on machines
running the Linux kernel where L<posix_fadvise(2)> can be used to
drop caches for a particular file after L<fsync(2)>.

dtas-archive spawns L<sox(1)> to archive audio data (likely uncompressed
WAVE) to FLAC and verifies the result using L<sndfile-cmp(1)>, a tool
implemented by different than sox and less likely to share the same bugs
(if any) as sox.

=head1 OPTIONS

=over

=item -j, --jobs [JOBS]

Number of jobs to run in parallel.  Incrementing this may hurt
performance on slow storage devices.  Default: 1

=item -n, --dry-run

Print, but do not run the commands to be executed

=item -s, --quiet, --silent

Silent operation, commands are not printed as executed

=item -S, --stats

Run and save the text output of the sox "stats" effect as
$DESTINATION_FILE_WITHOUT_SUFFIX.stats next to the output file

=item -k, --keep-going

Continue after error

=item -r, --repeat [COUNT]

Number of times to repeat the L<sndfile-cmp(1)> check.  Default: 1

=back

=head1 COPYRIGHT

Copyright 2013-2016 all contributors L<mailto:dtas-all@nongnu.org>

License: GPL-3.0+ L<https://www.gnu.org/licenses/gpl-3.0.txt>

=head1 CONTACT

All feedback welcome via plain-text mail to: L<mailto:dtas-all@nongnu.org>

Mailing list archives available at L<https://80x24.org/dtas-all/>
and L<https://lists.gnu.org/archive/html/dtas-all/>

No subscription is necessary to post to the mailing list.

=head1 SEE ALSO

L<sndfile-cmp(1)>, L<sox(1)>
